//Home
export const FETCH_STARTED = 'FETCH_STARTED';
export const FETCH_RECENTS = 'FETCH_RECENTS';
export const POST_NEW_PASTE = 'POST_NEW_PASTE';
export const POST_NEW_PASTE_SUCCEEDED = 'POST_NEW_PASTE_SUCCEEDED';
export const RESET_POST_DATA = 'RESET_POST_DATA';

//Paste
export const FETCH_PASTE_BY_ID = 'FETCH_PASTE_BY_ID';
