export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const INCREMENT = 'INCREMENT';
export const FETCH_RECENTS = 'FETCH_RECENTS';
